version: '3.1'

services:
  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
  mongo-seed:
    build: mongo-seed
    restart: on-failure
    environment:
      MONGO_HOST: mongo
      MONGO_COLLECTION: songs
      MONGO_FILE: songs.json
    depends_on:
      - mongo
